### ISSUE TITLE
Testing feature

### ISSUE THREAD

**Issue by chloehumphrey** [cs-450-project/se-phase1#21]
- Implement Jest to run unit tests on our program
- I believe Copilot can assist with this to some extent

MODE 3: RUN TESTS

Sample Command: "./run test"

Sample Output (to Stdout):

Total: 10
Passed: 9
Coverage: 90%
9/10 test cases passed. 90% line coverage achieved.

**Comment by chloehumphrey** [comment]
In class, he talked about adding CI testing to the GitHub repository. This would probably make our lives a lot easier lol. It seems like this can be implemented with Jest and it's basically auto testing whenever someone pushes to the repo.

**Comment by adhabib** [comment]
Currently having trouble with the "coverage" part of the output. Currently, everything else outputs fine, but coverage just says 0%. CoPilot has not been much help, even after inserting debugging code.

**Comment by chloehumphrey** [comment]
Moving from Jest to Vitest.
