### ISSUE TITLE
Add additional logging statements.

### ISSUE THREAD

**Issue by chloehumphrey** [cs-450-project/se-phase1#50]
We need to add some more logging statements to the program.

Instead of importing pino to every file, I've created a logger.ts config file. This is setup to output to a file specified in the .env file. 

Setting the program up with logging:
1. Create 'logs' folder in the root directory
Add these lines to your '.env' file:
2. LOG_LEVEL = 1
3. LOG_FILE = ./logs/app.log
Run normally, you'll see the file fill up

LOG_LEVELs:
0 : silent
1: info
2: debug
3: error

- [x] Add logging to the metric classes
- [x] Make sure we're adding "debug" logging statements in addition to "info"

**Comment by WillKissel02** [comment]
Closed in #58
