### ISSUE TITLE
Deliverable report

### ISSUE THREAD

**Issue by chloehumphrey** [cs-450-project/se-phase1#52]
The [deliverable report](https://purdue0-my.sharepoint.com/:w:/r/personal/humphr30_purdue_edu/_layouts/15/Doc.aspx?sourcedoc=%7B9BA1EB85-0479-401D-B67B-ED64D5257728%7D&file=Phase1-DeliverableReport.docx&action=default&mobileredirect=true) is a substantial amount of points for our project.

When filling out the deliverable report, make sure you consider the [initial Project Spec](https://purdue0-my.sharepoint.com/:w:/r/personal/humphr30_purdue_edu/_layouts/15/Doc.aspx?sourcedoc=%7B8C2F3E20-3920-4357-9F5D-509BAD6B73B1%7D&file=Phase1-ProjectSpec.docx&action=default&mobileredirect=true) and our [Project Plan (Milestone 1)](https://purdue0-my.sharepoint.com/:w:/r/personal/humphr30_purdue_edu/_layouts/15/Doc.aspx?sourcedoc=%7B5151A3B6-C2C5-4C25-8CE1-0952DCBC38AF%7D&file=Group4-Phase1-ProjectPlan.docx&action=default&mobileredirect=true)

**Comment by WillKissel02** [comment]
Report was submitted
